packages:
  - packages/*

catalogs:
  eslint:
    '@eslint/js': ^9.39.2
    eslint: ^9.39.2
    globals: ^16.5.0
    typescript-eslint: ^8.51.0
  eslint-react:
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
  hardhat:
    '@nomicfoundation/hardhat-verify': ^3.0.8
    '@nomicfoundation/hardhat-viem': ^3.0.1
    hardhat: ^3.1.1
    solhint: ^6.0.2
  openzeppelin:
    '@openzeppelin/contracts': 4.9.6
    '@openzeppelin/contracts-upgradeable': 4.9.6
  prettier:
    prettier: ^3.7.4
    prettier-plugin-solidity: ^2.2.1
  react:
    '@tanstack/react-query': ^5.90.15
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3
  typescript:
    '@types/node': ^22.19.3
    typescript: ^5.9.3
  verax:
    '@verax-attestation-registry/verax-contracts': 10.0.0
    '@verax-attestation-registry/verax-sdk': 5.0.0
  vite:
    '@vitejs/plugin-react': ^5.1.2
    vite: ^7.3.0
  wagmi:
    '@reown/appkit': ^1.8.15
    '@reown/appkit-adapter-wagmi': ^1.8.15
    wagmi: ^3.1.3
  web3:
    viem: ^2.43.3

overrides:
  bl@<0.9.5: '>=0.9.5'
  bl@<1.2.3: '>=1.2.3'
  nanoid@>=4.0.0 <5.0.9: '>=5.0.9'
  parse-duration@<2.1.3: '>=2.1.3'
  semver@<4.3.2: '>=4.3.2'
  semver@<5.7.2: '>=5.7.2'
