packages:
  - packages/*

overrides:
  bl@<0.9.5: '>=0.9.5'
  bl@<1.2.3: '>=1.2.3'
  cookie@<0.7.0: '>=0.7.0'
  nanoid@>=4.0.0 <5.0.9: '>=5.0.9'
  parse-duration@<2.1.3: '>=2.1.3'
  semver@<4.3.2: '>=4.3.2'
  semver@<5.7.2: '>=5.7.2'
  tmp@<=0.2.3: '>=0.2.4'
